server:
  port: 8082

spring:
  application:
    name: payment-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/emprestimosdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect